services:
  - type: web
    name: moodmusic-backend
    env: python
    plan: free
    rootDir: backend
    pythonVersion: "3.10.13"
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: FLASK_DEBUG
        value: "false"
